default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 12345678

development:
  <<: *default
  database: development_db_film

test:
  <<: *default
  database: test_db_film

production:
  <<: *default
  database: production_db_film
