# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b93b585f62ae2bd8e185b9a54bef9b36a09e6fae94a45d4811a8b3f7b176e7afc0b747ed0bdafeee7d888374898e5d3762e31a2a2edd9e6008424358f54c7cd

test:
  secret_key_base: 47117b711e458afefc4649d33f0df7a6092cbdebf0987fae01b016fe3ae913ccea6656c428c73a509927e5a7f2f8dac635a3cf81000a88b3868ba6ee9986ff29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
