user:
  username:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
film:
  paginates_per: 5
category:
  paginates_per: 10
schedule:
  paginates_per: 7
order:
  paginates_per: 10
review:
  paginates_per: 5
  maximum: 200
films:
  format_gio: "%H:%M"
  format_ngay: "%d/%m/%Y"
  format_day: "%d"
  format_m: "%m"
  format_y: "%Y"
